server:
  port: 8081
spring:
  application:
    name: transaction-processor
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
ledgerflow:
  provider:
    base-url: ${PROVIDER_BASE_URL:http://localhost:8082}
    connect-timeout: ${PROVIDER_CONNECT_TIMEOUT:1s}
    read-timeout: ${PROVIDER_READ_TIMEOUT:2s}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

